### ISSUE TITLE
NetCore client final cherrypick edition

### ISSUE THREAD

**Issue by bartelink** [EventStore/EventStore#1719]
@jageall I have extracted this from a polluting comment thread in #1716 - I have removed my comment, can you remove your response and put it here please (I know it should be in NetCore). When you paste here I'll respond. The TL;DR is that mine has a concurrency fix, but the more important one was done by Hayley IIRC (will dig it up). Also if you are doing a final cherrypick, I'd like to have  KeepDiscovering pulled in too. Apologies for not doing the due diligence  of pointing this out over there - but I really didnt want to encourage persisting with two code bases.
> I am not sure that saying the client connects half-successfully is really even vaguely accurate as it has 1000s of hours of use. I have observed problems with reconnection and some settings not working as expected

Repeating, but I feel its important to state that there are two significant concurrency fixes in 4.1.1 - I've destruction tested it with various combinations of killing and restarting servers, sockets etc, after various outages and have not seen it fail. (Also we put plenty load inc all sorts of DDOS attack effects through it on a regular basis problem free). The current NetCore client fails at the very first hurdle on my most basic load test rig for, to me, obvious reasons (concurrency bugs), which manifest as a disconnection with a complete failure to automatically reconnect. (The same basic problems exist in 3.9.x). We also have some prod NetCore stuff failing load tests for the same [for me entirely obvious] reason. It is for these reasons (aside from wanting feature parity and less messy builds) that I was eager to have #1680 expedited.

As long as the eye is on the goal of having a netstandard build of the ClientAPI in EventStore/EventStore/master being on NuGet (at least as an alpha) real soon, this overall plan is obviously in everyone's interest (feel free to ping me the minute one is available and I'll run it on my rig - I really hope that will before I get that rig open sourced, which will be this year). (I don't want to oversell the rig - it just runs hundreds of client threads against a single EventStoreConnection connecting with gossip [to a local instance for most of my testing])

**Comment by bartelink** [comment]
@jageall Preview - will re-post at tail after you re-post your response  here
Wishlist/need list in order of age sequence I think they need to be applied in:
1. Depending on messiness, `PreferSlaveNode` is nice to have in order to be able to trust semantics to be equivalent https://github.com/EventStore/EventStore/pull/1557 and https://github.com/EventStore/EventStore/pull/1559
2. Most critical concurrency fix IME is @hayley-jean's `ConcurrentDictionary` https://github.com/EventStore/EventStore/pull/1561
3. I think I build on https://github.com/EventStore/EventStore/pull/1567 so best to take
4. Would be nice to have `KeepDiscovering` API, and it's small: https://github.com/EventStore/EventStore/pull/1578
5. My feature includes a concurrency bugfix (and is critical to be able to deal with backlogs under load without swamping servers): https://github.com/EventStore/EventStore/pull/1582
6. Fix bug so discovery does not throw on localhost: https://github.com/EventStore/EventStore/pull/1600
Finally can I ask that it be called something other than 4.1.1 - while I think this is pretty much full bug and feature compat with it, we don't know that for a fact and I'd hate to have people making bad assumptions

**Comment by bartelink** [comment]
Final suggestion though: https://github.com/EventStore/EventStore/pull/1680 pretty much achieves all of this - and could actually be legitimately labelled `4.1.1`. I reckon using that is actually the best way to get a reliable NetCore client into the field.

I can appreciate that you/ES might not wish to stand over it and/or invest the time - but you could label it `-alpha1`

Either way, I'll test an alpha/RC if/when it arrives a) with my load test rig b) by re-running a (currently failing) prod load test against a prod cluster (assuming that works it'll be in prod pretty quick - I simply don't trust the code as it is given the ample evidence and logical reasons not to)

**Comment by jageall** [comment]
For ease i will revert the pr that causes the codebases to diverge and do a
full 4.1.1 compatibility release candidate . I will then publish an rc.
Once you have verified it passes your tests i will do a 4.1.1 release (some
people need a non rc version to put into prod). I will then ask all the
current prs to be redone against the main client or move them myself.

I do hear all that you are saying, but would rather a final release with
full parity before switching over.

Re your test rig. I have been discussing the need for more rigorous load
testing of all the client features against a cluster that has failovers
occuring as part of the release process. I am pretty sure this will happen,
but i dont have timescales for achieving it.

If you are unable to open source your rig, i am sure your input would be
valued when we do that work.

Again thanks for your help and apologies again about the misunderstanding
on my part.

**Comment by jageall** [comment]
#1561 is a serverside fix? Is that the correct one or did you mean a other?

**Comment by bartelink** [comment]
Don't have time to peep right now, but I remember it being that kinda shape - I also recall doing a history of stuff touching ClientApi and something like that being in the mix. What I am certain of is that the 4.0.1 Nuget and the NetCore one failed in the same way and there were not a lot of commits - ~April.

The test rig we/I have is at its core a perf+load test (i.e. the idea for https://github.com/EventStore/EventStore/issues/1652 arises for its perf when threads get into conflict on the same stream); it just happens to be a good soak/resilience test for the client as a side-effect, but there is good scope to extend it. Failure injections are not part of it though - i.e. I was closing sockets with tcpview and killing servers with Ctrl C.

I'll see if I can establish a timeline as to when it can hit the open; there's a full set of client wrappers etc. which all need to generate NuGets and have good build pipelines before I release them. One other important blocker was that I was hoping to avoid the extra build work to make it target NetCore.ClientAPI and normal Client API conditionally, which is what https://github.com/EventStore/EventStore/pull/1680 was supposed to alleviate ;)

**Comment by jageall** [comment]
Ok, I have published an rc with all the changes moved across to the core client. Hopefully it will fix the problems with the core client.

Just to be clear, the core client was a personal project to get the client working on core, which is why it was a bit behind (read very busy with paying work) However, as i am now working on getting the unified client/core build fairly heavily, if there are changes required that you find in your load testing, i will try and update the client asap.

**Comment by bartelink** [comment]
This is awesome James - will be in touch, hopefully over the weekend. The fact you did this in the first instance is and was much appreciated from everyone's perspective.

**Comment by bartelink** [comment]
Still seeing what I believe to be the same behavior (and an exception that suggests one of the commits re IPv6 localhost handling is not included). Have done zero digging - perhaps I should start from trying a binary from #1680 - but we can to/fro if you DM me.
```
[17:25:02 INF] Running for 00:10:00, targeting localhost with heartbeat: 00:00:01.5000000, max concurrent requests: 5000
Test freq 4000 hits/s; Operation timeout: 00:00:03 and 1 retries; max errors: 3000
Reporting intervals: ["00:10:00", "00:00:10", "00:01:00", "00:05:00"], report file: \bin\Release\netcoreapp2.0\log.txt
[17:25:03 INF] Discovering: found best choice [127.0.0.1:1113,n/a] (Master).
[17:25:03 INF] Discovering: found best choice [127.0.0.1:1113,n/a] (Master).
[17:25:03 INF] Discovering attempt 1/2147483647 successful: best candidate is [127.0.0.1:1113, n/a].
[17:25:03 INF] Discovering attempt 1/2147483647 successful: best candidate is [127.0.0.1:1113, n/a].
[17:25:03 INF] Initializing session pool count=8000
[17:25:03 INF] Session pool ready
[17:25:03 INF] Load test started
[17:25:14 INF] Aggregate:
Bucket   : span=10s timestamp=2018-09-08T17:25:13
Tests    : total=4323 success=3262 OperationTimedOutException=1061
Latency  : max=9.74s p99=9.076s p95=8.468s p50=4.386s min=1.759s avg=4.758s stddev=2.289s
[17:25:18 INF] ClientAPI TcpConnection closed [16:25:18.508: N127.0.0.1:1113, L127.0.0.1:57702, {edf6e266-0f34-4879-b71b-23a1ba6f7ac0}]:
[17:25:18 INF] Received bytes: 522950, Sent bytes: 2632735
[17:25:18 INF] Send calls: 13075, callbacks: 13075
[17:25:18 INF] Receive calls: 184, callbacks: 184
[17:25:18 INF] Close reason: [Success] Socket closed
[17:25:23 INF] Discovering attempt 1/2147483647 failed: no candidate found.
[17:25:23 INF] Aggregate:
Bucket   : span=10s timestamp=2018-09-08T17:25:23
Tests    : total=5415 success=5415
Latency  : max=16.76s p99=13.24s p95=12.37s p50=11.97s min=8.5s avg=11.64s stddev=0.903s
[17:25:24 INF] Discovering attempt 2/2147483647 failed with error: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Receive(String method, String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader)
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Get(String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader)
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.TryGetGossipFrom(GossipSeed endPoint)
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<DiscoverEndPoint>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<DiscoverAsync>d__10.MoveNext().
[17:25:25 INF] Discovering: found best choice [127.0.0.1:1113,n/a] (Master).
[17:25:25 INF] Discovering attempt 3/2147483647 successful: best candidate is [127.0.0.1:1113, n/a].
[17:25:31 INF] ClientAPI TcpConnection closed [16:25:31.632: N127.0.0.1:1113, L127.0.0.1:57701, {cbbd9d6d-4aa0-4ccd-a780-829bd2996cec}]:
[17:25:34 INF] Received bytes: 26257303, Sent bytes: 6978183
[17:25:34 INF] Send calls: 83076, callbacks: 83076
[17:25:34 INF] Receive calls: 10675, callbacks: 10675
[17:25:34 INF] Close reason: [Success] Socket closed
[17:25:33 INF] Aggregate:
Bucket   : span=10s timestamp=2018-09-08T17:25:32
Tests    : total=1 success=1
Latency  : max=23.26s p99=23.26s p95=23.26s p50=23.26s min=23.26s avg=23.26s stddev=NaNs
[17:25:39 INF] ClientAPI TcpConnection closed [16:25:39.885: N127.0.0.1:1113, L127.0.0.1:57705, {7920d016-448e-41bc-b492-b945c4b53544}]:
[17:25:39 INF] Received bytes: 1654254, Sent bytes: 3693060
[17:25:39 INF] Send calls: 19759, callbacks: 19759
[17:25:39 INF] Receive calls: 934, callbacks: 934
[17:25:39 INF] Close reason: [Success] Socket closed
```

**Comment by bartelink** [comment]
WAIT... - I think I'm getting an incorrect DLL version actually being included in the build :doh:

**Comment by jageall** [comment]
I had some problems with publishing the package so it might be my fault,
but i thought i published it ok. I cant see what i missed re ipv6 but will
test it when i get back. Sadly almost none of the changes had tests to
verify they were working. Something i would like to get fixed.

**Comment by bartelink** [comment]
Hm, will remove the log above and replace with a better one later on. It's no longer hanging, but it is getting into a bad state which it does not in normal FW where it's losing connection. This might be down to perf differences and related necessary timeout adjustments... So, it's back to watch this space, sorry!

**Comment by jageall** [comment]
No problem. Thank you very much for.your work on this

**Comment by bartelink** [comment]
OK, more preliminary results:- it's not hanging, and the APIs and bugfixes are in. I need to spend some time later to dig deeper into the perf and will report back (I have never been in a position to do a comparison as my record run was about 5s on the old version of the NetCore client). So 🤞 but looking good atm.

**Comment by jageall** [comment]
Watching this space :)

**Comment by bartelink** [comment]
... Seeing a `StackOverflowException` on long runs [but long runs actually being possible is a step up]. Will report if/when I get to take a deeper look

**Comment by jageall** [comment]
Send me the stack trace if you can. I was suspicious of some of the
changes. It also might be a difference in the jit between core and full
framework

**Comment by bartelink** [comment]
Have not been able to repro this situation on 5.x in recent times despite trying so am closing this as can't repro. That does not mean it's absolutely definitely gone (I've had VMWare Fusion foisted on me which has destroyed disk perf), but I've definitely tried and don't think the issue is adding value in its open state.
