### ISSUE TITLE
MergeIndexes endpoint returns class name, not result

### ISSUE THREAD

**Issue by anthonyMc11** [EventStore/EventStore#3432]
I'm using eventstore  21.6.0.0

reproduction steps: 
1. Make a request as the admin user to this endpoint : POST /admin/mergeindexes
2. wait for response

Expected result: a summary

Actual: the name of the class: _EventStore.Core.Messages.MergeIndexesResultDto_

![image](https://user-images.githubusercontent.com/2892217/154655442-b6731503-82e3-4e67-87bb-46d628675c3e.png)

**Comment by oskardudycz** [comment]
Thanks, we plan to fix it in an upcoming release.

p.s. I also recommend switching to the LTS release, as `xx.2` and `xx.6` releases are only supported until the next LTS is released. 21.10 contains already a lot of potential fixes and fully working persistent subscriptions to $all.

**Comment by anthonyMc11** [comment]
Thanks, I'll consider upgrading is there a version number the fix is due in?

**Comment by timothycoleman** [comment]
Hi @anthonyMc11, this is fixed in the upcoming 22.10.0 release (which is also an LTS release). I'll close this for now, feel free to reopen if you have any problems

**Comment by anthonyMc11** [comment]
hi @timothycoleman  I've retested on eventstore version 21.10.8.0 and I'm still getting the same behaviour
